# -*- coding: utf-8 -*-
"""
method_docs_data.py — Contenido fuente de la documentación técnica (Tarea 4).

Una sola fuente de verdad para los 32 métodos del Optimizador, usada por
generate_docs.py para producir tanto el .docx como el .pdf sin duplicar
contenido. Los parámetros/fórmulas citados aquí están tomados directamente
de la implementación real (no son valores genéricos de libro de texto) —
ver commits de la Tarea 4 para el detalle de dónde se verificó cada uno.
"""
from __future__ import annotations

# ─── Categorías ────────────────────────────────────────────────────────────
CATEGORIES = [
    "Unidimensionales (1D)",
    "Basados en gradiente/Newton (ND, sin restricción)",
    "Metaheurísticos (globales, sin gradiente)",
    "Restringidos (MD) — penalización / barrera / suma",
    "Multiobjetivo — técnicas clásicas (Schaffer genérico)",
    "Multiobjetivo — motor de escalarización (Fase 6-8)",
]

# ─── 1. Unidimensionales ────────────────────────────────────────────────────
METHODS = [
dict(nombre="Búsqueda Local", categoria=CATEGORIES[0],
    formula="Evalúa f(x), f(x+p), f(x−p); se mueve al mejor punto que mejore estrictamente; si ninguno mejora, p ← p/2.",
    descripcion="Búsqueda de patrón 1D con paso adaptativo (variante simple tipo Hooke-Jeeves), no requiere derivadas.",
    requisitos="Función evaluable en el rango [lo,hi]; no requiere continuidad ni derivabilidad.",
    convergencia="Se detiene cuando el paso p < tolerancia (1e-5) o tras 100 iteraciones. Lineal, sensible al paso inicial (0.1).",
    ventajas="Muy simple; no necesita derivadas; robusta ante funciones no suaves.",
    desventajas="Lenta cerca del óptimo; puede estancarse en funciones con muchos mínimos locales muy cercanos entre sí.",
    cuando_usar="Introducción a búsqueda 1D; funciones no diferenciables o ruidosas.",
    cuando_no_usar="Funciones multivariable (solo acepta 1 variable); cuando se necesita velocidad de convergencia alta.",
    compatibles="Cualquier función real de 1 variable, continua o no.",
    incompatibles="Funciones de 2+ variables (bloqueado con mensaje claro).",
    ejemplo="f(x) = x² − 4x + 5  →  x* ≈ 2, f* ≈ 1"),

dict(nombre="Fibonacci", categoria=CATEGORIES[0],
    formula="Reducción de intervalo con razones de Fibonacci: x₁=a+(F_{N-2}/F_N)(b−a), x₂=a+(F_{N-1}/F_N)(b−a).",
    descripcion="Búsqueda de sección 1D que minimiza el número de evaluaciones de f para una tolerancia objetivo dada.",
    requisitos="Función unimodal en [lo,hi] (un único mínimo en el intervalo) para garantía teórica de convergencia.",
    convergencia="El parámetro L (tolerancia) fija cuántos términos de Fibonacci se generan (objetivo = (b−a)/L); óptimamente eficiente en número de evaluaciones para funciones unimodales.",
    ventajas="Mínimo número de evaluaciones de f entre los métodos de reducción de intervalo; determinístico.",
    desventajas="Requiere unimodalidad — en funciones con varios mínimos puede converger a uno subóptimo sin avisar.",
    cuando_usar="Funciones costosas de evaluar, unimodales, 1 variable.",
    cuando_no_usar="Funciones multivariable o claramente multimodales en el rango elegido.",
    compatibles="Funciones reales de 1 variable, idealmente unimodales en [lo,hi].",
    incompatibles="2+ variables; L (tolerancia) ≤ 0 (bloqueado con mensaje).",
    ejemplo="f(x) = x² − 4x + 5, L=0.1  →  x* ≈ 2"),

dict(nombre="Sección Áurea", categoria=CATEGORIES[0],
    formula="Igual que Fibonacci pero con razón fija τ=(√5−1)/2≈0.618 en vez de razones de Fibonacci calculadas.",
    descripcion="Golden-section search: reduce el intervalo en la razón áurea, reutilizando una evaluación de f por iteración.",
    requisitos="Función unimodal en [lo,hi].",
    convergencia="Se detiene cuando el intervalo (b−a) < 1e-6, máx. 200 iteraciones. Convergencia lineal con razón τ≈0.618.",
    ventajas="No necesita precalcular una secuencia como Fibonacci; igual de simple y robusta.",
    desventajas="Ligeramente menos eficiente que Fibonacci en evaluaciones totales (óptimo teórico es Fibonacci).",
    cuando_usar="Alternativa a Fibonacci cuando no se quiere fijar una tolerancia L explícita.",
    cuando_no_usar="Funciones multivariable; funciones no unimodales.",
    compatibles="Funciones reales de 1 variable, unimodales en [lo,hi].",
    incompatibles="2+ variables (bloqueado con mensaje claro).",
    ejemplo="f(x) = x² − 4x + 5  →  x* ≈ 2"),

dict(nombre="Sección Dorada", categoria=CATEGORIES[0],
    formula="Misma técnica que «Sección Áurea» (razón áurea τ); en la app es la variante usada además como sub-rutina interna de los métodos multiobjetivo escalarizados.",
    descripcion="Golden-section search — nombre distinto de «Sección Áurea» en el combo por motivos históricos del proyecto, mismo algoritmo base.",
    requisitos="Función unimodal en [lo,hi].",
    convergencia="Igual que Sección Áurea.",
    ventajas="Igual que Sección Áurea; además es el solver interno de todas las técnicas de escalarización MO.",
    desventajas="Igual que Sección Áurea.",
    cuando_usar="Igual que Sección Áurea.",
    cuando_no_usar="Funciones multivariable; no unimodales.",
    compatibles="Funciones reales de 1 variable, unimodales.",
    incompatibles="2+ variables.",
    ejemplo="f(x) = x² − 4x + 5  →  x* ≈ 2"),

dict(nombre="Goldstein", categoria=CATEGORIES[0],
    formula="Descenso de gradiente con condiciones de Goldstein: f₀+μα(g·d) ≤ f(x+αd) ≤ f₀+(1−μ)α(g·d), μ=0.2.",
    descripcion="Búsqueda de línea con doble cota (ni muy poco ni demasiado avance) sobre la dirección de máximo descenso d=−∇f.",
    requisitos="f diferenciable (gradiente vía SymPy exacto); acepta 1 o más variables.",
    convergencia="Detiene cuando ‖∇f‖ < 1e-7; backtracking α←0.5α hasta 50 intentos internos por iteración externa.",
    ventajas="Evita pasos demasiado cortos (a diferencia de Armijo puro), mejorando la velocidad práctica.",
    desventajas="Usa descenso de gradiente puro (no Newton) — convergencia más lenta que métodos de segundo orden en problemas mal condicionados.",
    cuando_usar="Funciones diferenciables donde Armijo converge muy lento por pasos pequeños.",
    cuando_no_usar="Funciones no diferenciables (Abs, signo, etc. en puntos no suaves).",
    compatibles="Funciones diferenciables, 1 o más variables.",
    incompatibles="Funciones no derivables en la trayectoria de búsqueda.",
    ejemplo="f(x) = x² − 4x + 5  →  x* ≈ 2"),

dict(nombre="Newton-Raphson", categoria=CATEGORIES[0],
    formula="x_{k+1} = x_k − (H+regI)⁻¹∇f(x_k), con búsqueda de línea de respaldo si el paso no mejora f.",
    descripcion="Newton clásico con regularización automática del Hessiano (reg=1e-10, ×10 hasta 8 intentos) y respaldo a descenso de gradiente si sigue singular.",
    requisitos="f dos veces diferenciable (Hessiano exacto vía SymPy); 1 o más variables.",
    convergencia="Cuadrática cerca del óptimo si el Hessiano es bien condicionado; detiene con ‖∇f‖ < 1e-6, máx. 50 iteraciones.",
    ventajas="Convergencia muy rápida (cuadrática) cerca del mínimo; robusta a Hessianos casi singulares gracias a la regularización.",
    desventajas="Cada iteración es más cara (requiere Hessiano); puede alejarse del óptimo si el punto inicial está lejos y la función no es convexa.",
    cuando_usar="Funciones suaves, dos veces diferenciables, buen punto inicial.",
    cuando_no_usar="Funciones no diferenciables; alta dimensión (costo del Hessiano crece como n²).",
    compatibles="Funciones C² (dos veces diferenciables), 1 o más variables.",
    incompatibles="Funciones con puntos no derivables (Abs, Max no suave, etc.) en la trayectoria.",
    ejemplo="f(x) = x² − 4x + 5  →  x* = 2 en 1 iteración (cuadrática exacta)"),

dict(nombre="Grad. Conjugado", categoria=CATEGORIES[1],
    formula="Fletcher-Reeves: β_k=‖g_{k+1}‖²/‖g_k‖²; d_{k+1}=−g_{k+1}+β_k·d_k. Reinicio a −g cada max(n,5) iteraciones.",
    descripcion="Gradiente conjugado no lineal (variante Fletcher-Reeves) con backtracking Armijo (c1=1e-4) para el tamaño de paso.",
    requisitos="f diferenciable; pensado para multivariable (n≥2), aunque acepta también 1 variable.",
    convergencia="Detiene con ‖∇f‖ < 1e-6, máx. 100 iteraciones; en problemas cuadráticos converge en a lo sumo n pasos.",
    ventajas="No necesita almacenar/invertir el Hessiano — mucho más barato que Newton en alta dimensión.",
    desventajas="Sensible a la precisión de la búsqueda de línea; en problemas no cuadráticos puede perder la propiedad de conjugación sin reinicios frecuentes.",
    cuando_usar="Problemas multivariable de dimensión media/alta donde el Hessiano es costoso.",
    cuando_no_usar="Funciones no diferenciables.",
    compatibles="Funciones diferenciables, cualquier número de variables.",
    incompatibles="Funciones no derivables en la trayectoria.",
    ejemplo="f(x1,x2) = (x1−2)²+(x2−1)²  →  converge en pocos pasos"),

dict(nombre="Armijo", categoria=CATEGORIES[1],
    formula="Newton con paso de Armijo: d_k = H⁻¹(−g_k) (o −g_k si H singular); acepta α si f(x+αd) ≤ f_k+μ·α·(g_k·d_k), μ=0.6, α←0.8α.",
    descripcion="Newton multivariable con búsqueda de línea de descenso suficiente (condición de Armijo) por retroceso.",
    requisitos="f diferenciable (gradiente y Hessiano exactos vía SymPy); acepta 1 o más variables.",
    convergencia="Detiene con ‖∇f‖ < 1e-6, máx. 50 iteraciones; si el Hessiano es singular, detiene inmediatamente (sin respaldo a descenso puro, a diferencia de Newton-Raphson).",
    ventajas="Combina la velocidad de Newton con una garantía simple de descenso suficiente; sencillo de razonar.",
    desventajas="Sin respaldo si el Hessiano es singular (se detiene ahí, a diferencia de Newton-Raphson que sí tiene fallback); solo controla descenso, no evita pasos demasiado cortos (a diferencia de Goldstein/Wolfe).",
    cuando_usar="Funciones diferenciables, multivariable, con Hessiano razonablemente bien condicionado.",
    cuando_no_usar="Funciones no diferenciables (p. ej. Abs en un punto no suave) — el cálculo simbólico de la derivada falla con un error claro.",
    compatibles="Funciones diferenciables, cualquier número de variables.",
    incompatibles="Funciones no derivables (Abs/sign/Piecewise no suaves en el punto de evaluación).",
    ejemplo="f(x1,x2) = 2(x1−3)²+x1·x2³, con x0=[0,0]"),

dict(nombre="Wolfe", categoria=CATEGORIES[1],
    formula="Newton con condición de curvatura fuerte: |∇f(x+αd)ᵀd| ≤ μ·|∇f(x)ᵀd|, μ=0.6, resuelta por bisección en α∈[0,1].",
    descripcion="Newton multivariable con búsqueda de línea que garantiza curvatura adecuada (evita pasos demasiado cortos), vía bisección — no incluye la condición de descenso suficiente por separado (queda desacoplada de Armijo en esta implementación).",
    requisitos="f diferenciable (gradiente y Hessiano exactos); acepta 1 o más variables.",
    convergencia="Bisección detiene si la condición de curvatura se cumple o el intervalo (v−u) < 1e-7, máx. 20 iteraciones internas.",
    ventajas="Evita pasos demasiado cortos, favoreciendo avance más agresivo que Armijo puro.",
    desventajas="Al no combinar explícitamente la condición de descenso suficiente en el mismo paso, no es un Wolfe estándar de libro de texto (fuerte/débil) sino una variante simplificada centrada en curvatura.",
    cuando_usar="Funciones diferenciables donde Armijo converge muy lento (pasos demasiado cortos).",
    cuando_no_usar="Funciones no diferenciables.",
    compatibles="Funciones diferenciables, cualquier número de variables.",
    incompatibles="Funciones no derivables en la trayectoria.",
    ejemplo="f(x1,x2) = 2(x1−3)²+x1·x2³, con x0=[0,0]"),

dict(nombre="SA: Recocido Simulado", categoria=CATEGORIES[2],
    formula="Enfriamiento geométrico T←0.95·T; vecino x'=x+N(0,0.3); acepta si ΔE<0, o con prob. exp(−ΔE/T).",
    descripcion="Metaheurística de recocido simulado: T_init=100, T_min=1e-4, máx. 500 iteraciones, semilla fija (reproducible).",
    requisitos="Función evaluable en el rango; no requiere continuidad ni derivabilidad.",
    convergencia="Probabilística/heurística, no garantizada; detiene por T<T_min o iteraciones agotadas. Guarda el mejor punto visto, no solo el actual.",
    ventajas="Escapa de mínimos locales gracias a la aceptación probabilística; robusta ante ruido y discontinuidades.",
    desventajas="No determinística en el sentido de garantía de óptimo global; requiere ajustar el enfriamiento para problemas difíciles.",
    cuando_usar="Funciones con muchos mínimos locales, no diferenciables, o ruidosas.",
    cuando_no_usar="Cuando se necesita una garantía de convergencia exacta/determinística, o el presupuesto de evaluaciones es muy bajo.",
    compatibles="Cualquier función evaluable (continua, discontinua, no diferenciable), 1 o más variables (vía bounds).",
    incompatibles="Ninguna restricción estructural — el rango [lo,hi] siempre debe ser válido (lo<hi).",
    ejemplo="f(x) = x² − 4x + 5, rango [0,5]"),

dict(nombre="PSO: Enjambre", categoria=CATEGORIES[2],
    formula="v←w·v+c1·r1·(pbest−x)+c2·r2·(gbest−x), w=0.7, c1=c2=1.5; posición recortada a [lo,hi].",
    descripcion="Particle Swarm Optimization: 30 partículas, 150 iteraciones máx. (config. de la app), semilla fija.",
    requisitos="Función evaluable en el rango [lo,hi]; no requiere derivabilidad.",
    convergencia="Heurística; detiene antes si gbest<1e-10 o la diversidad del enjambre cae por debajo de 1e-8.",
    ventajas="Buena exploración global; fácil de paralelizar conceptualmente; pocos hiperparámetros.",
    desventajas="Puede converger prematuramente en problemas muy multimodales si w/c1/c2 no están bien ajustados; sin garantía de óptimo global.",
    cuando_usar="Funciones multimodales, no diferenciables, con rango acotado conocido.",
    cuando_no_usar="Cuando se requiere precisión muy alta cerca del óptimo (mejor refinar después con un método de gradiente).",
    compatibles="Cualquier función evaluable en un rango acotado, 1 o más variables.",
    incompatibles="Rango inválido (lo≥hi, bloqueado con mensaje).",
    ejemplo="f(x) = x² − 4x + 5, rango [0,5]"),

dict(nombre="GA: Algoritmo Genético", categoria=CATEGORIES[2],
    formula="Selección por torneo (k=3); cruce aritmético (blend, α=0.5); mutación gaussiana adaptativa σ=0.3(1−g/max_gen)+0.02; elitismo=3.",
    descripcion="Algoritmo genético real-valued: población 50, 150 generaciones máx., p_cruce=0.8, p_mutación=0.15.",
    requisitos="Función evaluable en el rango [lo,hi]; no requiere derivabilidad.",
    convergencia="Heurística; detiene antes si el mejor f<1e-10 o la diversidad poblacional cae por debajo de 1e-9.",
    ventajas="Muy robusta ante funciones discontinuas, ruidosas o con múltiples óptimos; el elitismo evita perder buenas soluciones.",
    desventajas="Puede requerir muchas evaluaciones de f para converger con precisión; sensible a los parámetros de mutación en problemas de alta dimensión.",
    cuando_usar="Funciones muy irregulares, con múltiples mínimos locales similares.",
    cuando_no_usar="Presupuesto de evaluaciones muy limitado, o se necesita precisión numérica alta cerca del óptimo.",
    compatibles="Cualquier función evaluable en un rango acotado, 1 o más variables.",
    incompatibles="Rango inválido (lo≥hi).",
    ejemplo="f(x) = x² − 4x + 5, rango [0,5]"),

dict(nombre="MD: Penalización (Newton)", categoria=CATEGORIES[3],
    formula="φ(x)=f(x)+μ·max(0,g(x))², μ←10μ en 3 pasadas externas (μ₀=1); resuelto con Newton propio regularizado por pasada.",
    descripcion="Penalización exterior cuadrática clásica para g(x)≤0, con solver interno Newton+Armijo.",
    requisitos="Requiere g(x) — sin restricción, la penalización no hace nada. Interpreta g(x)≤0 como restricción de desigualdad; una sola restricción por corrida.",
    convergencia="3 pasadas externas con μ creciendo ×10; cada pasada converge cuando ‖∇φ‖≤1e-6, máx. 60 iteraciones internas.",
    ventajas="Simple de entender y depurar; no requiere punto inicial factible (a diferencia de barrera).",
    desventajas="Mal condicionamiento numérico cuando μ crece mucho; solo admite g(x)≤0 (no igualdades, no múltiples restricciones).",
    cuando_usar="Enseñar/demostrar penalización exterior; punto inicial infactible.",
    cuando_no_usar="Sin restricción definida (bloqueado); restricciones de igualdad puras o múltiples restricciones simultáneas (no soportado).",
    compatibles="f y g diferenciables, 1+ variables, con g(x) definida.",
    incompatibles="Sin g(x) (bloqueado con mensaje y recomendación); funciones no diferenciables.",
    ejemplo="f=(x1−2)²+(x2−1)², g=x1+x2−2  →  x*≈[1.5,0.5], f*≈0.5"),

dict(nombre="MD: Barreras (Newton)", categoria=CATEGORIES[3],
    formula="φ(x)=f(x)−(1/t)·log(−g(x)), t←10t en 3 pasadas (t₀=1); requiere punto factible interior g(x)<0.",
    descripcion="Método de barrera logarítmica (interior point clásico) para g(x)<0 estricta, con solver interno Newton.",
    requisitos="Requiere g(x). Si x0 es infactible, la app empuja automáticamente x0 a lo largo de −∇g hasta 50 pasos, o aplica un jitter si no lo logra.",
    convergencia="3 pasadas con t creciendo ×10; cada pasada usa línea de búsqueda que preserva factibilidad (α se reduce hasta que g(x_new)<0), converge con ‖∇φ‖≤1e-6.",
    ventajas="Mantiene siempre un punto factible durante toda la trayectoria — útil para visualizar cómo se acerca a la frontera de la restricción.",
    desventajas="Requiere estrictamente g(x)<0 (desigualdad estricta); numéricamente más delicado que penalización si el punto inicial está muy cerca de la frontera.",
    cuando_usar="Cuando importa mantener factibilidad en cada iteración (interpretación tipo interior-point).",
    cuando_no_usar="Restricciones de igualdad (g(x)=0 no tiene interior, la barrera no aplica); sin g(x) definido.",
    compatibles="f y g diferenciables, 1+ variables, restricción de desigualdad estricta.",
    incompatibles="Sin g(x); restricciones de igualdad.",
    ejemplo="f=(x1−2)²+(x2−1)², g=x1+x2−2  →  x*≈[1.495,0.495], f*≈0.51"),

dict(nombre="MD: Pen. (BFGS)", categoria=CATEGORIES[3],
    formula="Misma penalización cuadrática que «MD: Penalización (Newton)» (φ=f+μ·max(0,g)²), resuelta con BFGS (scipy) en vez de Newton propio.",
    descripcion="Compara el efecto del solver interno (BFGS cuasi-Newton vs. Newton exacto) manteniendo fija la técnica de restricción.",
    requisitos="Requiere g(x). Igual que Penalización (Newton) en la formulación matemática.",
    convergencia="3 pasadas externas, μ×10 cada una; BFGS converge superlinealmente sin necesitar el Hessiano exacto.",
    ventajas="No requiere Hessiano simbólico (más barato por iteración que Newton en dimensión alta); BFGS suele ser más robusto ante Hessianos mal condicionados.",
    desventajas="Convergencia superlineal, no cuadrática — puede necesitar más iteraciones que Newton cerca del óptimo.",
    cuando_usar="Comparar el efecto del solver interno; problemas donde el Hessiano exacto es costoso o inestable.",
    cuando_no_usar="Sin g(x) (bloqueado).",
    compatibles="f y g diferenciables (BFGS solo necesita gradiente, aproxima el Hessiano), 1+ variables.",
    incompatibles="Sin g(x).",
    ejemplo="f=(x1−2)²+(x2−1)², g=x1+x2−2  →  x*≈[1.5,0.5], f*≈0.5"),

dict(nombre="MD: Pes. (BFGS)", categoria=CATEGORIES[3],
    formula="Penalización LINEAL de peso creciente: φ(x)=f(x)+w·max(0,g(x)), w←5w en 3 pasadas (w₀=1), resuelta con BFGS.",
    descripcion="A diferencia de la penalización cuadrática, aquí el costo de violar la restricción crece linealmente — permite comparar el efecto de la forma de la penalización, no solo del solver.",
    requisitos="Requiere g(x).",
    convergencia="3 pasadas externas con w creciendo ×5; BFGS converge por pasada.",
    ventajas="La penalización exacta lineal puede forzar factibilidad con un peso finito (a diferencia de la cuadrática, que en teoría necesita μ→∞); útil para contrastar ambas formas.",
    desventajas="El término lineal introduce un punto no diferenciable en g(x)=0 (vía max(0,·)), lo que puede ralentizar la convergencia de un solver basado en gradiente como BFGS cerca de la frontera.",
    cuando_usar="Comparar penalización lineal vs. cuadrática; funciones acotadas.",
    cuando_no_usar="Sin g(x) (bloqueado); funciones no acotadas donde un peso pequeño no basta para contener la divergencia.",
    compatibles="f y g diferenciables, 1+ variables, idealmente f acotada.",
    incompatibles="Sin g(x).",
    ejemplo="f=(x1−2)²+(x2−1)², g=x1+x2−2  →  x*≈[1.5,0.5], f*≈0.5"),

dict(nombre="MD: Pes. (Nelder-Mead)", categoria=CATEGORIES[3],
    formula="Misma penalización lineal que «MD: Pes. (BFGS)» (φ=f+w·max(0,g), w←5w en 3 pasadas), resuelta con Nelder-Mead (sin derivadas, scipy).",
    descripcion="Compara un solver sin gradiente (simplex de Nelder-Mead) contra uno con gradiente (BFGS), con la misma técnica de restricción.",
    requisitos="Requiere g(x). No necesita que f o g sean diferenciables (Nelder-Mead solo evalúa la función).",
    convergencia="Más lenta y con más iteraciones que los solvers basados en gradiente; sin garantía teórica fuerte en dimensión alta.",
    ventajas="Funciona incluso si f o g no son diferenciables en algún punto; no requiere gradiente ni Hessiano.",
    desventajas="Más iteraciones/evaluaciones que BFGS; en funciones no acotadas el simplex puede explorar regiones muy alejadas (divergencia) si el peso no crece lo suficiente.",
    cuando_usar="f o g con puntos no diferenciables; se prefiere no depender de derivadas simbólicas.",
    cuando_no_usar="Sin g(x); funciones donde ya se sabe que el gradiente exacto está disponible y es barato (mejor usar BFGS/Newton, más eficientes).",
    compatibles="Cualquier f y g evaluables (no necesitan ser diferenciables), 1+ variables.",
    incompatibles="Sin g(x).",
    ejemplo="f=(x1−2)²+(x2−1)², g=x1+x2−2  →  x*≈[1.5,0.5], f*≈0.5"),

dict(nombre="MD: Sum. (BFGS)", categoria=CATEGORIES[3],
    formula="Suma ingenua de una sola pasada, sin escalar peso: h(x)=f(x)+g(x), resuelta con BFGS.",
    descripcion="Contraejemplo pedagógico: a diferencia de penalización/barrera, no hay ninguna pasada externa que aumente el costo de violar la restricción.",
    requisitos="Requiere g(x); sin él, degenera en un BFGS sin restricción sobre f.",
    convergencia="Una sola corrida de BFGS — mucho más rápida, pero sin ninguna garantía de que el resultado respete g(x)≤0.",
    ventajas="Extremadamente simple y rápida; útil para mostrar por qué las técnicas de penalización/barrera con peso creciente son necesarias.",
    desventajas="En general NO fuerza la factibilidad — el óptimo de h(x)=f(x)+g(x) casi nunca coincide con el óptimo restringido real, y en funciones no acotadas puede diverger.",
    cuando_usar="Únicamente con fines demostrativos/comparativos frente a los otros 5 métodos MD.",
    cuando_no_usar="Cuando se necesita una solución que realmente respete la restricción — usar Penalización o Barrera en su lugar.",
    compatibles="f y g diferenciables, 1+ variables (con fines demostrativos).",
    incompatibles="Sin g(x) (bloqueado); no debe usarse cuando se requiere factibilidad garantizada.",
    ejemplo="f=(x1−2)²+(x2−1)², g=x1+x2−2  →  x*≈[1.5,0.5], f*≈0.5 (coincide aquí porque el problema es simple; no es garantía general)"),

dict(nombre="Escalarización (Suma Ponderada)", categoria=CATEGORIES[5],
    formula="φ(x)=w₁f₁(x)+w₂f₂(x), pesos normalizados a partir de α: w=[α,1−α].",
    descripcion="Técnica de escalarización más simple e intuitiva; combina F(x)=[f1,f2] en un único escalar ponderado.",
    requisitos="f(x) mono-objetivo de 1 variable (la app genera f1=f(x) y f2=(x−x_centro)² automáticamente); resuelto internamente con Sección Dorada.",
    convergencia="La de Sección Dorada sobre φ(x,α): lineal con razón áurea.",
    ventajas="Simple, rápida, fácil de interpretar el efecto de α.",
    desventajas="No captura frentes de Pareto cóncavos (zonas del frente que la suma ponderada nunca puede alcanzar, sin importar los pesos).",
    cuando_usar="Frente de Pareto convexo; se necesita un resultado rápido con pesos intuitivos.",
    cuando_no_usar="Frente de Pareto con regiones cóncavas — usar NBI o Restricción Normal en su lugar.",
    compatibles="f(x) de exactamente 1 variable.",
    incompatibles="Funciones de 2+ variables (bloqueado con mensaje: «no se pudo aplicar este tipo de estudio»).",
    ejemplo="f(x) = (x−3)², α=0.5"),

dict(nombre="MO — Bisección", categoria=CATEGORIES[4],
    formula="Bisección sobre φ'(x,α)=0, donde φ(x,α)=α·f1(x)+(1−α)·f2(x).",
    descripcion="Técnica clásica del proyecto (previa al motor de escalarización): resuelve la suma ponderada por bisección en vez de sección áurea.",
    requisitos="f(x) mono-objetivo de 1 variable.",
    convergencia="Bisección estándar, lineal, tolerancia configurable.",
    ventajas="Determinística, fácil de trazar paso a paso para fines didácticos.",
    desventajas="Igual limitación que suma ponderada: no cubre frentes cóncavos.",
    cuando_usar="Fines didácticos, ver el proceso de bisección aplicado a MO.",
    cuando_no_usar="Frente cóncavo; funciones multivariable.",
    compatibles="f(x) de 1 variable.",
    incompatibles="2+ variables.",
    ejemplo="f(x) = (x−3)², α=0.5"),

dict(nombre="MO — Sección Dorada", categoria=CATEGORIES[4],
    formula="Igual que Bisección pero resolviendo φ(x,α) con búsqueda de sección áurea.",
    descripcion="Variante didáctica de suma ponderada resuelta con sección áurea en vez de bisección.",
    requisitos="f(x) mono-objetivo de 1 variable.",
    convergencia="Lineal, razón áurea.",
    ventajas="Igual que Bisección; consistente con el solver usado por el resto del motor de escalarización.",
    desventajas="Igual limitación de convexidad que suma ponderada.",
    cuando_usar="Fines didácticos.",
    cuando_no_usar="Frente cóncavo; funciones multivariable.",
    compatibles="f(x) de 1 variable.",
    incompatibles="2+ variables.",
    ejemplo="f(x) = (x−3)², α=0.5"),

dict(nombre="MO — Frente de Pareto", categoria=CATEGORIES[4],
    formula="Barrido de α∈[0,1] en 80 puntos; para cada α, Newton en φ'(x,α)=0 (hasta 100 iteraciones), registra (f1(x*),f2(x*)).",
    descripcion="Genera el frente de Pareto completo (no un solo punto) recorriendo todos los pesos α posibles.",
    requisitos="f(x) mono-objetivo de 1 variable.",
    convergencia="Newton por cada punto del barrido: cuadrática localmente; el barrido en sí es exhaustivo, no iterativo.",
    ventajas="Da la visión completa del frente, no solo un punto — ideal para elegir un compromiso informado entre f1 y f2.",
    desventajas="Más costoso computacionalmente (80 resoluciones de Newton); solo aplica a f1/f2 generados desde una función 1D.",
    cuando_usar="Se quiere explorar todo el frente antes de decidir un compromiso.",
    cuando_no_usar="Cuando ya se sabe exactamente qué α se necesita (más rápido usar Suma Ponderada directamente).",
    compatibles="f(x) de 1 variable.",
    incompatibles="2+ variables.",
    ejemplo="f(x) = (x−3)²  →  80 puntos del frente (f1,f2)"),

dict(nombre="MO — Análisis Jacobiano", categoria=CATEGORIES[4],
    formula="J(x)=[f1'(x), f2'(x)] en 15 puntos de [lo,hi]; λ=J_{f2}/(J_{f2}−J_{f1}); Pareto-óptimo si 0≤λ≤1.",
    descripcion="Verifica la condición de estacionariedad de Pareto (KKT 1D) en una malla de puntos, sin resolver una optimización.",
    requisitos="f(x) mono-objetivo de 1 variable, diferenciable.",
    convergencia="No iterativo — evaluación directa del Jacobiano en 15 puntos fijos.",
    ventajas="Muy rápido; permite ver directamente qué regiones del dominio son Pareto-óptimas sin resolver un problema de optimización.",
    desventajas="Solo evalúa 15 puntos discretos — puede pasar por alto regiones Pareto-óptimas estrechas entre dos puntos de la malla.",
    cuando_usar="Análisis exploratorio rápido de estacionariedad antes de optimizar formalmente.",
    cuando_no_usar="Cuando se necesita el óptimo exacto, no solo un diagnóstico.",
    compatibles="f(x) de 1 variable, diferenciable.",
    incompatibles="2+ variables; funciones no diferenciables.",
    ejemplo="f(x) = (x−3)²  →  tabla de 15 puntos con λ y ‖J‖"),
]

# ─── Motor de escalarización (Fase 6-8) — 9 técnicas ───────────────────────
_SCALAR_COMMON = dict(
    requisitos="f(x) mono-objetivo de 1 variable (la app construye F(x)=[f1,f2] automáticamente); resuelto con Sección Dorada.",
    convergencia="La del solver interno (Sección Dorada): lineal, razón áurea.",
    cuando_no_usar="Funciones de 2+ variables (el motor de escalarización opera sobre F(x)=[f1,f2] generado desde una f(x) de 1 variable, no sobre funciones ya multivariable).",
    compatibles="f(x) de exactamente 1 variable.",
    incompatibles="Funciones de 2+ variables (bloqueado con mensaje profesional).",
)
METHODS += [
dict(nombre="MO — Lexicográfico", categoria=CATEGORIES[5],
    formula="φ=f₍₁₎+ε·f₍₂₎+ε²·f₍₃₎+…  (prioridad fija f1≻f2, ε→0 aproxima el orden lexicográfico exacto).",
    descripcion="Optimiza estrictamente por orden de prioridad: primero minimiza f1 sin importar f2, salvo por el término ε que desempata.",
    ventajas="Modela preferencias jerárquicas claras («el costo importa más que el nivel de servicio, sin excepción»).",
    desventajas="Ignora casi por completo el objetivo secundario salvo para desempatar — no da control fino sobre el balance entre objetivos.",
    cuando_usar="Cuando un objetivo es estrictamente más importante que los demás (no hay trade-off aceptable).",
    **_SCALAR_COMMON,
    ejemplo="f(x) = (x−3)²"),

dict(nombre="MO — Goal Programming", categoria=CATEGORIES[5],
    formula="φ=Σ wᵢ·|fᵢ(x)−metaᵢ|^p  (p=1 por defecto).",
    descripcion="Define una meta aspiracional por objetivo y minimiza las desviaciones ponderadas respecto a esas metas.",
    ventajas="Muy intuitivo para el usuario de negocio: «quiero costo ≤ X y servicio ≥ Y», no pesos abstractos.",
    desventajas="El resultado depende fuertemente de qué tan realistas sean las metas elegidas; metas inalcanzables distorsionan la solución.",
    cuando_usar="Cuando el decisor puede expresar metas concretas por objetivo (satisfacer en vez de optimizar puro).",
    **_SCALAR_COMMON,
    ejemplo="f(x) = (x−3)², metas = punto ideal"),

dict(nombre="MO — ε-Constraint", categoria=CATEGORIES[5],
    formula="φ=f_primario(x)+1e6·Σ max(0, fᵢ(x)−εᵢ)²  (i≠primario).",
    descripcion="Deja un objetivo como función a minimizar y convierte los demás en restricciones (fᵢ≤εᵢ) con penalización cuadrática.",
    ventajas="Da control directo sobre el nivel de servicio aceptable; la interpretación es clara y la solución es fácil de justificar.",
    desventajas="Requiere elegir ε con cuidado — un ε mal elegido puede volver el problema infactible o trivial.",
    cuando_usar="Hay un objetivo dominante claro y los demás son restricciones de servicio.",
    **_SCALAR_COMMON,
    ejemplo="f(x) = (x−3)², ε calculado a partir de la tabla de pagos"),

dict(nombre="MO — ASF (Logro)", categoria=CATEGORIES[5],
    formula="φ=max_i[wᵢ(fᵢ(x)−zᵢ)] + ρ·Σ(fᵢ(x)−zᵢ)  (Wierzbicki, ρ=1e-4).",
    descripcion="Función de logro (Achievement Scalarizing Function): minimiza la máxima distancia ponderada a un punto de referencia z (típicamente el punto ideal).",
    ventajas="Puede alcanzar cualquier punto del frente de Pareto (incluso en regiones cóncavas), a diferencia de la suma ponderada.",
    desventajas="La función max(·) no es diferenciable en el punto de cambio de objetivo dominante — puede requerir más iteraciones del solver.",
    cuando_usar="Se quiere explorar todo el frente de Pareto, incluidas regiones cóncavas.",
    **_SCALAR_COMMON,
    ejemplo="f(x) = (x−3)², punto de referencia = ideal"),

dict(nombre="MO — Chebyshev", categoria=CATEGORIES[5],
    formula="φ=max_i[wᵢ·|fᵢ(x)−zᵢ*|]  (zᵢ* = punto ideal).",
    descripcion="Distancia mínima ponderada al punto ideal en norma infinito (Chebyshev ponderado).",
    ventajas="Como ASF, cubre todo el frente de Pareto (cóncavo o convexo) variando los pesos.",
    desventajas="No diferenciable en el punto de cambio de objetivo dominante; sensible a la elección del punto ideal.",
    cuando_usar="Se quiere el punto del frente más cercano (en norma ∞) al ideal, con control de pesos.",
    **_SCALAR_COMMON,
    ejemplo="f(x) = (x−3)², punto ideal calculado de la tabla de pagos"),

dict(nombre="MO — NBI", categoria=CATEGORIES[5],
    formula="t(x)=((F(x)−z̄)·n)/‖n‖²; φ=‖(F(x)−z̄)−t·n‖² − η·t  (Normal Boundary Intersection simplificado, η=0.1).",
    descripcion="Busca la intersección del frente de Pareto con una línea normal al segmento entre los puntos extremos de la tabla de pagos — genera puntos bien distribuidos en el frente.",
    ventajas="Distribución más uniforme de puntos en el frente que la suma ponderada, incluso en frentes con curvatura variable.",
    desventajas="Requiere la tabla de pagos (payoff table) precomputada; formulación más compleja de interpretar que suma ponderada.",
    cuando_usar="Se necesita un muestreo bien distribuido del frente de Pareto completo.",
    **_SCALAR_COMMON,
    ejemplo="f(x) = (x−3)², tabla de pagos 2×2"),

dict(nombre="MO — Restricción Normal", categoria=CATEGORIES[5],
    formula="φ=f_representativo(x)+1e6·max(0, (F(x)−z̄)·n)²  (Normal Constraint).",
    descripcion="Variante de NBI: fija un objetivo representativo y restringe el movimiento a lo largo de la dirección normal mediante penalización.",
    ventajas="Como NBI, produce puntos bien distribuidos; más simple de implementar/depurar que NBI puro.",
    desventajas="Igual dependencia de la tabla de pagos; el peso de penalización (1e6) puede requerir ajuste fino en problemas mal escalados.",
    cuando_usar="Alternativa a NBI cuando se prefiere una formulación de penalización en vez de proyección exacta.",
    **_SCALAR_COMMON,
    ejemplo="f(x) = (x−3)², tabla de pagos 2×2"),

dict(nombre="MO — Peso Adaptativo", categoria=CATEGORIES[5],
    formula="φ=Σwᵢfᵢ(x) − curvature_penalty·min_j‖F(x)−pⱼ‖²  (Adaptive Weighted Sum).",
    descripcion="Extiende la suma ponderada con un término que penaliza la cercanía a puntos vecinos ya encontrados, empujando hacia regiones no exploradas del frente (incluidas cóncavas).",
    ventajas="Puede cubrir regiones cóncavas que la suma ponderada simple no alcanza, sin la formulación max(·) no diferenciable de ASF/Chebyshev.",
    desventajas="Requiere puntos vecinos (`neighbor_points`) para que el término de curvatura tenga efecto — sin ellos, se reduce a suma ponderada simple.",
    cuando_usar="Se está muestreando el frente iterativamente y se quiere evitar puntos redundantes.",
    **_SCALAR_COMMON,
    ejemplo="f(x) = (x−3)², sin puntos vecinos → equivale a suma ponderada"),

dict(nombre="MO — Punto de Referencia", categoria=CATEGORIES[5],
    formula="φ=max_i[wᵢ(fᵢ(x)−zᵢ)] + ρ·Σ(fᵢ(x)−zᵢ)  (misma fórmula que ASF, pero z es una aspiración libre, no necesariamente el ideal).",
    descripcion="Igual formulación matemática que ASF/Logro, pero pensada para que el decisor fije un punto de referencia propio (no necesariamente alcanzable), típico de métodos interactivos de decisión.",
    ventajas="Permite exploración interactiva: el decisor mueve el punto de referencia y ve cómo cambia la solución.",
    desventajas="Misma no-diferenciabilidad que ASF; el resultado depende fuertemente del punto de referencia elegido.",
    cuando_usar="Proceso interactivo de decisión donde el usuario ajusta su punto de referencia iterativamente.",
    **_SCALAR_COMMON,
    ejemplo="f(x) = (x−3)², punto de referencia = f(x0)"),
]

assert len(METHODS) == 32, f"Se esperaban 32 métodos, hay {len(METHODS)}"

# ─── Matriz de compatibilidad (resumen por categoría estructural) ─────────
COMPAT_MATRIX = [
    dict(tipo_funcion="1 variable, cualquier forma (continua, discontinua, no derivable)",
         compatibles="Búsqueda Local, SA, PSO, GA",
         incompatibles="—",
         nota="Los metaheurísticos y Búsqueda Local no requieren derivadas ni unimodalidad."),
    dict(tipo_funcion="1 variable, unimodal en [lo,hi]",
         compatibles="Fibonacci, Sección Áurea, Sección Dorada",
         incompatibles="Multimodal sin garantía (puede converger a un mínimo local no deseado, sin aviso)",
         nota="La unimodalidad no se valida automáticamente — es responsabilidad del usuario verificarla."),
    dict(tipo_funcion="1 variable o multivariable, diferenciable",
         compatibles="Goldstein, Newton-Raphson, Grad. Conjugado, Armijo, Wolfe",
         incompatibles="Funciones con puntos no derivables en la trayectoria (Abs, sign, Piecewise no suave) — bloqueado con mensaje claro y recomendación de método alternativo",
         nota="El gradiente/Hessiano se calcula simbólicamente vía SymPy; si sympy no puede derivar, el sistema traduce el error a un mensaje en español."),
    dict(tipo_funcion="Multivariable, CON restricción g(x)≤0 (o g(x)<0 estricta para Barreras)",
         compatibles="Los 6 métodos MD (Penalización, Barreras, Pen. BFGS, Pes. BFGS, Pes. Nelder-Mead, Sum. BFGS)",
         incompatibles="Sin g(x) definido — bloqueado con mensaje y recomendación de método sin restricción",
         nota="Una sola restricción de desigualdad por corrida; no soporta igualdades ni múltiples restricciones simultáneas."),
    dict(tipo_funcion="1 variable (base para F(x)=[f1,f2] generado automáticamente)",
         compatibles="Los 14 métodos multiobjetivo (Escalarización, MO—Bisección/Sección Dorada/Frente de Pareto/Análisis Jacobiano, y las 9 técnicas del motor de escalarización)",
         incompatibles="Funciones ya multivariable (2+ variables) — bloqueado con mensaje: «no se pudo aplicar este tipo de estudio a la expresión dada»",
         nota="El sistema NO acepta un F(x) multivariable directo: siempre parte de f(x) de 1 variable y genera f2 internamente."),
]
